package com.hibernate.mappings.entity;
// Generated Jun 9, 2023, 7:15:28 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Customeritem generated by hbm2java
 */
@Entity
@Table(name = "customeritem", catalog = "ravi")
public class Customeritem implements java.io.Serializable {

	private String id;
	private long customerId;
	private long itemId;

	public Customeritem() {
	}

	public Customeritem(String id, long customerId, long itemId) {
		this.id = id;
		this.customerId = customerId;
		this.itemId = itemId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 45)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "CustomerID", nullable = false)
	public long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	@Column(name = "ItemID", nullable = false)
	public long getItemId() {
		return this.itemId;
	}

	public void setItemId(long itemId) {
		this.itemId = itemId;
	}

}
