package com.hibernate.mappings.entity;
// Generated Jun 9, 2023, 12:23:06 PM by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Items generated by hbm2java
 */
@Entity
@Table(name = "items", catalog = "ravi")
public class Items implements java.io.Serializable {

	private long itemId;
	private String itemName;
	private String category;
	private String brand;
	private String color;
	private Double price;
	private String description;
	private Set<Customer> customers = new HashSet<Customer>(0);
	private Set<OrdersTable> ordersTables = new HashSet<OrdersTable>(0);

	public Items() {
	}

	public Items(long itemId) {
		this.itemId = itemId;
	}

	public Items(long itemId, String itemName, String category, String brand, String color, Double price,
			String description, Set<Customer> customers, Set<OrdersTable> ordersTables) {
		this.itemId = itemId;
		this.itemName = itemName;
		this.category = category;
		this.brand = brand;
		this.color = color;
		this.price = price;
		this.description = description;
		this.customers = customers;
		this.ordersTables = ordersTables;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "item_id", unique = true, nullable = false)
	public long getItemId() {
		return this.itemId;
	}

	public void setItemId(long itemId) {
		this.itemId = itemId;
	}

	@Column(name = "item_name", length = 45)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "category", length = 45)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "brand", length = 45)
	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	@Column(name = "color", length = 45)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "price", precision = 20, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToMany(mappedBy = "items",cascade = CascadeType.ALL)

	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

	@ManyToMany(mappedBy = "items",cascade = CascadeType.ALL)

	public Set<OrdersTable> getOrdersTables() {
		return this.ordersTables;
	}

	public void setOrdersTables(Set<OrdersTable> ordersTables) {
		this.ordersTables = ordersTables;
	}

}
