package com.hibernate.mappings.entity;
// Generated Jun 9, 2023, 12:23:06 PM by Hibernate Tools 4.3.6.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrdersTable generated by hbm2java
 */
@Entity
@Table(name = "orders_table", catalog = "ravi")
public class OrdersTable implements java.io.Serializable {

	private long id;
	private Customer customer;
	private int orderStatus;
	private String orderNumber;
	private Integer orderQuantity;
	private Double totalPrice;
	private Set<Items> items= new HashSet<Items>(0);

	public OrdersTable() {
	}

	public OrdersTable(long id, int orderStatus) {
		this.id = id;
		this.orderStatus = orderStatus;
	}

	public OrdersTable(long id, Customer customer, int orderStatus, String orderNumber, Integer orderQuantity,
			Double totalPrice, Set<Items> items) {
		this.id = id;
		this.customer = customer;
		this.orderStatus = orderStatus;
		this.orderNumber = orderNumber;
		this.orderQuantity = orderQuantity;
		this.totalPrice = totalPrice;
		this.items = items;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "order_status", nullable = false)
	public int getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(int orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "order_number")
	public String getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	@Column(name = "order_quantity")
	public Integer getOrderQuantity() {
		return this.orderQuantity;
	}

	public void setOrderQuantity(Integer orderQuantity) {
		this.orderQuantity = orderQuantity;
	}

	@Column(name = "total_price", length = 45)
	public Double getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(Double totalPrice) {
		this.totalPrice = totalPrice;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "orderitemjoin", catalog = "ravi", joinColumns = {
			@JoinColumn(name = "orderid", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "itemid", nullable = false, updatable = false) })
	public Set<Items> getItemses() {
		return this.items;
	}

	public void setItemses(Set<Items> items) {
		this.items = items;
	}

}
