package com.hibernate.mappings.entity;
// Generated Jun 9, 2023, 7:15:28 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Orderitemjoin generated by hbm2java
 */
@Entity
@Table(name = "orderitemjoin", catalog = "ravi")
public class Orderitemjoin implements java.io.Serializable {

	private String id;
	private long itemid;
	private long orderid;

	public Orderitemjoin() {
	}

	public Orderitemjoin(String id, long itemid, long orderid) {
		this.id = id;
		this.itemid = itemid;
		this.orderid = orderid;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 45)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "itemid", nullable = false)
	public long getItemid() {
		return this.itemid;
	}

	public void setItemid(long itemid) {
		this.itemid = itemid;
	}

	@Column(name = "orderid", nullable = false)
	public long getOrderid() {
		return this.orderid;
	}

	public void setOrderid(long orderid) {
		this.orderid = orderid;
	}

}
